/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_mux.h
**     Project     : MK02ECU
**     Processor   : MK02FN128VLF10
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-04-19, 19:17, # CodeGen: 20
**     Abstract    :
**
**     Settings    :
**          Component name                                 : pin_mux
**          PinSettings IP Block                           : PinSettings
**          Processor                                      : MK02FN128LF10
**          Pin settings                                   : 
**            Routing                                      : 
**              Peripheral Type ADC                        : 
**                Custom name                              : ADC0
**                ADC0                                     : 
**                  DM0 - Minus channel 0                  : ADC0_DM0
**                  DM1 - Minus channel 1                  : <Automatic>
**                  DM2 - Minus channel 2                  : <Automatic>
**                  DP0 - Plus channel 0                   : ADC0_DP0
**                  DP1 - Plus channel 1                   : <Automatic>
**                  DP2 - Plus channel 2                   : <Automatic>
**                  SE0 - Single-ended channel 0           : ADC0_DP0
**                  SE1 - Single-ended channel 1           : <Automatic>
**                  SE2 - Single-ended channel 2           : <Automatic>
**                  SE8 - Single-ended channel 8           : <Automatic>
**                  SE9 - Single-ended channel 9           : <Automatic>
**                  SE12 - Single-ended channel 12         : <Automatic>
**                  SE13 - Single-ended channel 13         : <Automatic>
**                  SE14 - Single-ended channel 14         : <Automatic>
**                  SE15 - Single-ended channel 15         : <Automatic>
**                  SE17 - Single-ended channel 17         : <Automatic>
**                  SE18 - Single-ended channel 18         : <Automatic>
**                  SE19 - Single-ended channel 19         : ADC0_DM0
**                  SE20 - Single-ended channel 20         : <Automatic>
**                  SE23 - Single-ended channel 23         : DAC0_OUT/CMP1_IN3/ADC0_SE23
**                  SE4a - Single-ended channel 4a         : <Automatic>
**                  SE5a - Single-ended channel 5a         : <Automatic>
**                  SE6a - Single-ended channel 6a         : <Automatic>
**                  SE7a - Single-ended channel 7a         : <Automatic>
**                  SE4b - Single-ended channel 4b         : <Automatic>
**                  SE5b - Single-ended channel 5b         : <Automatic>
**                  SE6b - Single-ended channel 6b         : <Automatic>
**                  SE7b - Single-ended channel 7b         : <Automatic>
**                  Trigger A input                        : <Automatic>
**                  Trigger B input                        : <Automatic>
**                  Voltage reference high                 : VDDA
**                  Voltage reference high                 : VREFH
**                  Voltage reference low                  : VREFL
**                  Voltage reference low                  : VSSA
**                Bool_ADC0                                : yes
**              Peripheral Type CMP                        : 
**                Custom name                              : CMP0
**                CMP0                                     : 
**                  IN0 - Input 0                          : <Automatic>
**                  IN1 - Input 1                          : <Automatic>
**                  IN5 - Input 5                          : VREF_OUT/CMP1_IN5/CMP0_IN5
**                  OUT - Comparator output                : <Automatic>
**                Bool_CMP0                                : yes
**                Custom name                              : CMP1
**                CMP1                                     : 
**                  IN0 - Input 0                          : <Automatic>
**                  IN1 - Input 1                          : <Automatic>
**                  IN3 - Input 3                          : DAC0_OUT/CMP1_IN3/ADC0_SE23
**                  IN5 - Input 5                          : VREF_OUT/CMP1_IN5/CMP0_IN5
**                  OUT - Comparator output                : <Automatic>
**                Bool_CMP1                                : yes
**              Peripheral Type CRC                        : 
**                Custom name                              : CRC
**              Peripheral Type CoreDebug                  : 
**              Peripheral Type DAC                        : 
**                Custom name                              : DAC0
**                DAC0                                     : 
**                  Output pin                             : DAC0_OUT/CMP1_IN3/ADC0_SE23
**                Bool_DAC0                                : yes
**              Peripheral Type DMA                        : 
**                Custom name                              : DMA
**              Peripheral Type DMAMUX                     : 
**                Custom name                              : DMAMUX
**              Peripheral Type DWT                        : 
**              Peripheral Type EWM                        : 
**                Custom name                              : EWM
**                EWM                                      : 
**                  Input pin                              : <Automatic>
**                  Output pin                             : <Automatic>
**                Bool_EWM                                 : yes
**              Peripheral Type FMC                        : 
**                Custom name                              : FMC
**              Peripheral Type FPB                        : 
**              Peripheral Type FTFA                       : 
**                Custom name                              : FTFA
**              Peripheral Type FTM                        : 
**                Custom name                              : FTM0
**                FTM0                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH2 - Channel 2                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH3 - Channel 3                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH4 - Channel 4                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH5 - Channel 5                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN0 - External clock input          : <Automatic>
**                  FLT0 - Fault input 0                   : <Automatic>
**                  FLT1 - Fault input 1                   : <Automatic>
**                  FLT2 - Fault input 2                   : <Automatic>
**                  FLT3 - Fault input 3                   : <Automatic>
**                  Trigger input 0                        : <Automatic>
**                  Trigger input 1                        : <Automatic>
**                  Trigger input 2                        : <Automatic>
**                Bool_FTM0                                : yes
**                Custom name                              : FTM1
**                FTM1                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN0 - External clock input          : <Automatic>
**                  FLT0 - Fault input 0                   : <Automatic>
**                  FLT1 - Fault input 1                   : <Automatic>
**                  Quadrature decoder phase A input       : <Automatic>
**                  Quadrature decoder phase B input       : <Automatic>
**                  Trigger input 0                        : <Automatic>
**                  Trigger input 1                        : <Automatic>
**                  Trigger input 2                        : <Automatic>
**                Bool_FTM1                                : yes
**                Custom name                              : FTM2
**                FTM2                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN0 - External clock input          : <Automatic>
**                  FLT0 - Fault input 0                   : <Automatic>
**                  FLT1 - Fault input 1                   : <Automatic>
**                  Trigger input 0                        : <Automatic>
**                Bool_FTM2                                : yes
**              Peripheral Type GPIO                       : 
**                Custom name                              : PTA
**                PTA                                      : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 18                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 19                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_PTA                                 : yes
**                Custom name                              : PTB
**                PTB                                      : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 16                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 17                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_PTB                                 : yes
**                Custom name                              : PTC
**                PTC                                      : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 6                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 7                                  : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_PTC                                 : yes
**                Custom name                              : PTD
**                PTD                                      : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 6                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 7                                  : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_PTD                                 : yes
**                Custom name                              : PTE
**                PTE                                      : 
**                  Pin 16                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 17                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 18                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 19                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 24                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 25                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_PTE                                 : yes
**              Peripheral Type I2C                        : 
**                Custom name                              : I2C0
**                I2C0                                     : 
**                  SCL - Serial clock                     : <Automatic>
**                  SDA - Serial data                      : <Automatic>
**                Bool_I2C0                                : yes
**              Peripheral Type ITM                        : 
**              Peripheral Type JTAG                       : 
**                JTAG                                     : 
**                  TCLK - Test clock                      : <Automatic>
**                  TDI - Test data input                  : <Automatic>
**                  TDO - Test data output                 : <Automatic>
**                  TMS - Test mode selection              : <Automatic>
**                Bool_JTAG                                : yes
**              Peripheral Type LLWU                       : 
**                Custom name                              : LLWU
**                LLWU                                     : 
**                  P3 - Wake-up pin 3                     : <Automatic>
**                  P5 - Wake-up pin 5                     : <Automatic>
**                  P6 - Wake-up pin 6                     : <Automatic>
**                  P7 - Wake-up pin 7                     : <Automatic>
**                  P8 - Wake-up pin 8                     : <Automatic>
**                  P9 - Wake-up pin 9                     : <Automatic>
**                  P10 - Wake-up pin 10                   : <Automatic>
**                  P12 - Wake-up pin 12                   : <Automatic>
**                  P13 - Wake-up pin 13                   : <Automatic>
**                  P14 - Wake-up pin 14                   : <Automatic>
**                  P15 - Wake-up pin 15                   : <Automatic>
**                Bool_LLWU                                : yes
**              Peripheral Type LPTMR                      : 
**                Custom name                              : LPTMR0
**                LPTMR0                                   : 
**                  Pulse counter input 0                  : <Automatic>
**                  Pulse counter input 1                  : <Automatic>
**                  Pulse counter input 2                  : <Automatic>
**                  Pulse counter input 3                  : <Automatic>
**                Bool_LPTMR0                              : yes
**              Peripheral Type MCG                        : 
**                Custom name                              : MCG
**              Peripheral Type MCM                        : 
**                Custom name                              : MCM
**              Peripheral Type NV                         : 
**                Custom name                              : FTFA_FlashConfig
**              Peripheral Type NVIC                       : 
**                Custom name                              : NVIC
**              Peripheral Type OSC                        : 
**                Custom name                              : OSC
**                OSC                                      : 
**                  External clock/oscillator input        : <Automatic>
**                  Oscillator output                      : <Automatic>
**                Bool_OSC                                 : yes
**              Peripheral Type PDB                        : 
**                Custom name                              : PDB0
**                PDB0                                     : 
**                  External trigger input                 : <Automatic>
**                Bool_PDB0                                : yes
**              Peripheral Type PIT                        : 
**                Custom name                              : PIT
**              Peripheral Type PMC                        : 
**                Custom name                              : PMC
**              Peripheral Type PORT                       : 
**                Custom name                              : PORTA
**                Custom name                              : PORTB
**                Custom name                              : PORTC
**                Custom name                              : PORTD
**                Custom name                              : PORTE
**              Peripheral Type RCM                        : 
**                Custom name                              : RCM
**                RCM                                      : 
**                  Reset input                            : RESET_b
**                Bool_RCM                                 : yes
**              Peripheral Type SCB                        : 
**                Custom name                              : SystemControl
**                SystemControl                            : 
**                  NMI - Non-maskable interrupt           : <Automatic>
**                Bool_SystemControl                       : yes
**              Peripheral Type SIM                        : 
**                Custom name                              : SIM
**                SIM                                      : 
**                  Clock generation SIM output            : <Automatic>
**                  SIM XOR input FTM1 channel 1           : <Automatic>
**                Bool_SIM                                 : yes
**              Peripheral Type SMC                        : 
**                Custom name                              : SMC
**              Peripheral Type SPI                        : 
**                Custom name                              : SPI0
**                SPI0                                     : 
**                  SPI peripheral chip select(output) 0 or slave select(input): <Automatic>
**                  Direction                              : <Automatic>
**                  PCS1 - Peripheral chip select 1        : <Automatic>
**                  PCS2 - Peripheral chip select 2        : <Automatic>
**                  PCS3 - Peripheral chip select 3        : <Automatic>
**                  PCS4 - Peripheral chip select 4        : <Automatic>
**                  SIN - Serial data in                   : <Automatic>
**                  SCK - Serial clock                     : <Automatic>
**                  Direction                              : <Automatic>
**                  SOUT - Serial data out                 : <Automatic>
**                Bool_SPI0                                : yes
**              Peripheral Type SUPPLY                     : 
**                SUPPLY                                   : 
**                  Chip power supply                      : VDD5
**                  Chip power supply                      : VDD51
**                  Analog power supply                    : VDDA
**                  Chip power ground                      : VSS6
**                  Chip power ground                      : VSS52
**                  Analog ground                          : VSSA
**                Bool_SUPPLY                              : yes
**              Peripheral Type SysTick                    : 
**                Custom name                              : SysTick
**              Peripheral Type TPIU                       : 
**                Custom name                              : TPIU
**                TPIU                                     : 
**                  Trace data                             : <Automatic>
**                Bool_TPIU                                : yes
**              Peripheral Type UART                       : 
**                Custom name                              : UART0
**                UART0                                    : 
**                  CTS - Clear to send                    : <Automatic>
**                  RTS - Request to send                  : <Automatic>
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_UART0                               : yes
**                Custom name                              : UART1
**                UART1                                    : 
**                  CTS - Clear to send                    : <Automatic>
**                  RTS - Request to send                  : <Automatic>
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_UART1                               : yes
**              Peripheral Type USB                        : 
**              Peripheral Type VREF                       : 
**                Custom name                              : VREF
**                VREF                                     : 
**                  Voltage reference output               : VREF_OUT/CMP1_IN5/CMP0_IN5
**                Bool_VREF                                : yes
**              Peripheral Type WDOG                       : 
**                Custom name                              : WDOG
**              Non-peripheral pins                        : 
**            Electrical properties                        : 
**              Pin 1: VDD5                                : 
**                Custom name, Signal name                 : VDD5
**              Pin 2: VSS6                                : 
**                Custom name, Signal name                 : VSS6
**              Pin 3: ADC0_SE4a/ADC0_DP1/PTE16/SPI0_PCS0/UART1_TX/FTM_CLKIN0/FTM0_FLT3: 
**                Custom name, Signal name                 : ADC0_SE4a/ADC0_DP1/PTE16/SPI0_PCS0/UART1_TX/FTM_CLKIN0/FTM0_FLT3
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 4: ADC0_SE5a/ADC0_DM1/PTE17/SPI0_SCK/UART1_RX/FTM_CLKIN1/LPTMR0_ALT3: 
**                Custom name, Signal name                 : ADC0_SE5a/ADC0_DM1/PTE17/SPI0_SCK/UART1_RX/FTM_CLKIN1/LPTMR0_ALT3
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 5: ADC0_SE6a/ADC0_DP2/PTE18/SPI0_SOUT/UART1_CTS_b/I2C0_SDA: 
**                Custom name, Signal name                 : ADC0_SE6a/ADC0_DP2/PTE18/SPI0_SOUT/UART1_CTS_b/I2C0_SDA
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 6: ADC0_SE7a/ADC0_DM2/PTE19/SPI0_SIN/UART1_RTS_b/I2C0_SCL: 
**                Custom name, Signal name                 : ADC0_SE7a/ADC0_DM2/PTE19/SPI0_SIN/UART1_RTS_b/I2C0_SCL
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 7: ADC0_DP0                            : 
**                Custom name, Signal name                 : ADC0_DP0
**              Pin 8: ADC0_DM0                            : 
**                Custom name, Signal name                 : ADC0_DM0
**              Pin 9: VDDA                                : 
**                Custom name, Signal name                 : VDDA
**              Pin 10: VREFH                              : 
**                Custom name, Signal name                 : VREFH
**              Pin 11: VREFL                              : 
**                Custom name, Signal name                 : VREFL
**              Pin 12: VSSA                               : 
**                Custom name, Signal name                 : VSSA
**              Pin 13: VREF_OUT/CMP1_IN5/CMP0_IN5         : 
**                Custom name, Signal name                 : VREF_OUT/CMP1_IN5/CMP0_IN5
**              Pin 14: DAC0_OUT/CMP1_IN3/ADC0_SE23        : 
**                Custom name, Signal name                 : DAC0_OUT/CMP1_IN3/ADC0_SE23
**              Pin 15: ADC0_SE17/PTE24/I2C0_SCL/EWM_OUT_b : 
**                Custom name, Signal name                 : ADC0_SE17/PTE24/I2C0_SCL/EWM_OUT_b
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 16: ADC0_SE18/PTE25/I2C0_SDA/EWM_IN    : 
**                Custom name, Signal name                 : ADC0_SE18/PTE25/I2C0_SDA/EWM_IN
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 17: PTA0/UART0_CTS_b/FTM0_CH5/JTAG_TCLK/SWD_CLK: 
**                Custom name, Signal name                 : PTA0/UART0_CTS_b/FTM0_CH5/JTAG_TCLK/SWD_CLK
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 18: PTA1/UART0_RX/JTAG_TDI             : 
**                Custom name, Signal name                 : PTA1/UART0_RX/JTAG_TDI
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 19: PTA2/UART0_TX/JTAG_TDO/TRACE_SWO   : 
**                Custom name, Signal name                 : PTA2/UART0_TX/JTAG_TDO/TRACE_SWO
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 20: PTA3/UART0_RTS_b/FTM0_CH0/JTAG_TMS/SWD_DIO: 
**                Custom name, Signal name                 : PTA3/UART0_RTS_b/FTM0_CH0/JTAG_TMS/SWD_DIO
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 21: PTA4/LLWU_P3/FTM0_CH1/NMI_b        : 
**                Custom name, Signal name                 : PTA4/LLWU_P3/FTM0_CH1/NMI_b
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 22: VDD51                              : 
**                Custom name, Signal name                 : VDD51
**              Pin 23: VSS52                              : 
**                Custom name, Signal name                 : VSS52
**              Pin 24: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0  : 
**                Custom name, Signal name                 : EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 25: XTAL0/PTA19/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1: 
**                Custom name, Signal name                 : XTAL0/PTA19/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 26: RESET_b                            : 
**                Custom name, Signal name                 : RESET_b
**              Pin 27: ADC0_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA: 
**                Custom name, Signal name                 : ADC0_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 28: ADC0_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM1_QD_PHB: 
**                Custom name, Signal name                 : ADC0_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM1_QD_PHB
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 29: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT3: 
**                Custom name, Signal name                 : ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT3
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 30: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/FTM0_FLT0: 
**                Custom name, Signal name                 : ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/FTM0_FLT0
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 31: PTB16/UART0_RX/FTM_CLKIN0/EWM_IN   : 
**                Custom name, Signal name                 : PTB16/UART0_RX/FTM_CLKIN0/EWM_IN
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 32: PTB17/UART0_TX/FTM_CLKIN1/EWM_OUT_b: 
**                Custom name, Signal name                 : PTB17/UART0_TX/FTM_CLKIN1/EWM_OUT_b
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 33: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG: 
**                Custom name, Signal name                 : ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 34: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0: 
**                Custom name, Signal name                 : ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 35: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1: 
**                Custom name, Signal name                 : ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 36: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT: 
**                Custom name, Signal name                 : CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 37: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/CMP1_OUT: 
**                Custom name, Signal name                 : PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/CMP1_OUT
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 38: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT/FTM0_CH2: 
**                Custom name, Signal name                 : PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT/FTM0_CH2
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 39: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG: 
**                Custom name, Signal name                 : CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 40: CMP0_IN1/PTC7/SPI0_SIN             : 
**                Custom name, Signal name                 : CMP0_IN1/PTC7/SPI0_SIN
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 41: PTD0/LLWU_P12/SPI0_PCS0            : 
**                Custom name, Signal name                 : PTD0/LLWU_P12/SPI0_PCS0
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Digital filter                           : <Automatic>
**              Pin 42: ADC0_SE5b/PTD1/SPI0_SCK            : 
**                Custom name, Signal name                 : ADC0_SE5b/PTD1/SPI0_SCK
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Digital filter                           : <Automatic>
**              Pin 43: PTD2/LLWU_P13/SPI0_SOUT/I2C0_SCL   : 
**                Custom name, Signal name                 : PTD2/LLWU_P13/SPI0_SOUT/I2C0_SCL
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Digital filter                           : <Automatic>
**              Pin 44: PTD3/SPI0_SIN/I2C0_SDA             : 
**                Custom name, Signal name                 : PTD3/SPI0_SIN/I2C0_SDA
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Digital filter                           : <Automatic>
**              Pin 45: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/EWM_IN: 
**                Custom name, Signal name                 : PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/EWM_IN
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Digital filter                           : <Automatic>
**              Pin 46: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/FTM0_CH5/EWM_OUT_b: 
**                Custom name, Signal name                 : ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/FTM0_CH5/EWM_OUT_b
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Digital filter                           : <Automatic>
**              Pin 47: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH0/FTM0_FLT0: 
**                Custom name, Signal name                 : ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH0/FTM0_FLT0
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Digital filter                           : <Automatic>
**              Pin 48: PTD7/UART0_TX/FTM0_CH1/FTM0_FLT1   : 
**                Custom name, Signal name                 : PTD7/UART0_TX/FTM0_CH1/FTM0_FLT1
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Digital filter                           : <Automatic>
**          Settings                                       : 
**            Clock gates initialization mode              : SIM HAL (fsl_sim_hal component)
**            Inherited HAL components                     : 
**              fsl_port_hal                               : fsl_port_hal
**              fsl_sim_hal                                : fsl_sim_hal
**              fsl_mcg_hal                                : fsl_mcg_hal
**     Contents    :
**         hardware_init          - void hardware_init(void);
**         init_gpio_pins         - void init_gpio_pins(uint32_t instance);
**         deinit_gpio_pins       - void deinit_gpio_pins(uint32_t instance);
**         init_jtag_pins         - void init_jtag_pins(uint32_t instance);
**         deinit_jtag_pins       - void deinit_jtag_pins(uint32_t instance);
**         init_llwu_pins         - void init_llwu_pins(uint32_t instance);
**         deinit_llwu_pins       - void deinit_llwu_pins(uint32_t instance);
**         init_tpiu_pins         - void init_tpiu_pins(uint32_t instance);
**         deinit_tpiu_pins       - void deinit_tpiu_pins(uint32_t instance);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.h
** @version 1.4
** @brief
**
*/         
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/         

#ifndef pin_mux_H_
#define pin_mux_H_

/* MODULE pin_mux. */


/*!
 * @brief ADC method sets registers according routing settings. Call
 *         this method code to route desired pins into ADC0 periphery.
 * @param instance - ADC instance number (0 is expected)
 */
void init_adc_pins(uint32_t instance);
/*!
 * @brief ADC method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for ADC0 periphery.
 * @param instance - ADC instance number (0 is expected)
 */
void deinit_adc_pins(uint32_t instance);
/*!
 * @brief CMP method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         CMP0, CMP1
 *         peripherals.
 * @param instance - CMP instance number 0..1
 */
void init_cmp_pins(uint32_t instance);
/*!
 * @brief CMP method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for:
 *         CMP0, CMP1
 *         peripherals.
 * @param instance - CMP instance number 0..1
 */
void deinit_cmp_pins(uint32_t instance);
/*!
 * @brief DAC method sets registers according routing settings. Call
 *         this method code to route desired pins into DAC0 periphery.
 * @param instance - DAC instance number (0 is expected)
 */
void init_dac_pins(uint32_t instance);
/*!
 * @brief DAC method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for DAC0 periphery.
 * @param instance - DAC instance number (0 is expected)
 */
void deinit_dac_pins(uint32_t instance);
/*!
 * @brief DMA method sets registers according routing settings. Call
 *         this method code to route desired pins into DMA periphery.
 * @param instance - DMA instance number (0 is expected)
 */
void init_dma_pins(uint32_t instance);
/*!
 * @brief DMA method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for DMA periphery.
 * @param instance - DMA instance number (0 is expected)
 */
void deinit_dma_pins(uint32_t instance);
/*!
 * @brief EWM method sets registers according routing settings. Call
 *         this method code to route desired pins into EWM periphery.
 * @param instance - EWM instance number (0 is expected)
 */
void init_ewm_pins(uint32_t instance);
/*!
 * @brief EWM method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for EWM periphery.
 * @param instance - EWM instance number (0 is expected)
 */
void deinit_ewm_pins(uint32_t instance);
/*!
 * @brief FTM method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         FTM0, FTM1, FTM2
 *         peripherals.
 * @param instance - FTM instance number 0..2
 */
void init_ftm_pins(uint32_t instance);
/*!
 * @brief FTM method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for:
 *         FTM0, FTM1, FTM2
 *         peripherals.
 * @param instance - FTM instance number 0..2
 */
void deinit_ftm_pins(uint32_t instance);
/*!
 * @brief GPIO method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         PTA, PTB, PTC, PTD, PTE
 *         peripherals.
 * @param instance - GPIO instance number 0..4
 */
void init_gpio_pins(uint32_t instance);
/*!
 * @brief GPIO method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for:
 *         PTA, PTB, PTC, PTD, PTE
 *         peripherals.
 * @param instance - GPIO instance number 0..4
 */
void deinit_gpio_pins(uint32_t instance);
/*!
 * @brief I2C method sets registers according routing settings. Call
 *         this method code to route desired pins into I2C0 periphery.
 * @param instance - I2C instance number (0 is expected)
 */
void init_i2c_pins(uint32_t instance);
/*!
 * @brief I2C method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for I2C0 periphery.
 * @param instance - I2C instance number (0 is expected)
 */
void deinit_i2c_pins(uint32_t instance);
/*!
 * @brief JTAG method sets registers according routing settings. Call
 *         this method code to route desired pins into JTAG periphery.
 * @param instance - JTAG instance number (0 is expected)
 */
void init_jtag_pins(uint32_t instance);
/*!
 * @brief JTAG method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for JTAG periphery.
 * @param instance - JTAG instance number (0 is expected)
 */
void deinit_jtag_pins(uint32_t instance);
/*!
 * @brief LLWU method sets registers according routing settings. Call
 *         this method code to route desired pins into LLWU periphery.
 * @param instance - LLWU instance number (0 is expected)
 */
void init_llwu_pins(uint32_t instance);
/*!
 * @brief LLWU method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for LLWU periphery.
 * @param instance - LLWU instance number (0 is expected)
 */
void deinit_llwu_pins(uint32_t instance);
/*!
 * @brief LPTMR method sets registers according routing settings. Call
 *         this method code to route desired pins into LPTMR0 periphery.
 * @param instance - LPTMR instance number (0 is expected)
 */
void init_lptmr_pins(uint32_t instance);
/*!
 * @brief LPTMR method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for LPTMR0 periphery.
 * @param instance - LPTMR instance number (0 is expected)
 */
void deinit_lptmr_pins(uint32_t instance);
/*!
 * @brief OSC method sets registers according routing settings. Call
 *         this method code to route desired pins into OSC periphery.
 * @param instance - OSC instance number (0 is expected)
 */
void init_osc_pins(uint32_t instance);
/*!
 * @brief OSC method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for OSC periphery.
 * @param instance - OSC instance number (0 is expected)
 */
void deinit_osc_pins(uint32_t instance);
/*!
 * @brief PDB method sets registers according routing settings. Call
 *         this method code to route desired pins into PDB0 periphery.
 * @param instance - PDB instance number (0 is expected)
 */
void init_pdb_pins(uint32_t instance);
/*!
 * @brief PDB method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for PDB0 periphery.
 * @param instance - PDB instance number (0 is expected)
 */
void deinit_pdb_pins(uint32_t instance);
/*!
 * @brief RCM method sets registers according routing settings. Call
 *         this method code to route desired pins into RCM periphery.
 * @param instance - RCM instance number (0 is expected)
 */
void init_rcm_pins(uint32_t instance);
/*!
 * @brief RCM method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for RCM periphery.
 * @param instance - RCM instance number (0 is expected)
 */
void deinit_rcm_pins(uint32_t instance);
/*!
 * @brief SCB method sets registers according routing settings. Call
 *         this method code to route desired pins into SystemControl periphery.
 * @param instance - SCB instance number (0 is expected)
 */
void init_scb_pins(uint32_t instance);
/*!
 * @brief SCB method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for SystemControl periphery.
 * @param instance - SCB instance number (0 is expected)
 */
void deinit_scb_pins(uint32_t instance);
/*!
 * @brief SIM method sets registers according routing settings. Call
 *         this method code to route desired pins into SIM periphery.
 * @param instance - SIM instance number (0 is expected)
 */
void init_sim_pins(uint32_t instance);
/*!
 * @brief SIM method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for SIM periphery.
 * @param instance - SIM instance number (0 is expected)
 */
void deinit_sim_pins(uint32_t instance);
/*!
 * @brief SPI method sets registers according routing settings. Call
 *         this method code to route desired pins into SPI0 periphery.
 * @param instance - SPI instance number (0 is expected)
 */
void init_spi_pins(uint32_t instance);
/*!
 * @brief SPI method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for SPI0 periphery.
 * @param instance - SPI instance number (0 is expected)
 */
void deinit_spi_pins(uint32_t instance);
/*!
 * @brief SUPPLY method sets registers according routing settings. Call
 *         this method code to route desired pins into SUPPLY periphery.
 * @param instance - SUPPLY instance number (0 is expected)
 */
void init_supply_pins(uint32_t instance);
/*!
 * @brief SUPPLY method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for SUPPLY periphery.
 * @param instance - SUPPLY instance number (0 is expected)
 */
void deinit_supply_pins(uint32_t instance);
/*!
 * @brief TPIU method sets registers according routing settings. Call
 *         this method code to route desired pins into TPIU periphery.
 * @param instance - TPIU instance number (0 is expected)
 */
void init_tpiu_pins(uint32_t instance);
/*!
 * @brief TPIU method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for TPIU periphery.
 * @param instance - TPIU instance number (0 is expected)
 */
void deinit_tpiu_pins(uint32_t instance);
/*!
 * @brief UART method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         UART0, UART1
 *         peripherals.
 * @param instance - UART instance number 0..1
 */
void init_uart_pins(uint32_t instance);
/*!
 * @brief UART method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for:
 *         UART0, UART1
 *         peripherals.
 * @param instance - UART instance number 0..1
 */
void deinit_uart_pins(uint32_t instance);
/*!
 * @brief VREF method sets registers according routing settings. Call
 *         this method code to route desired pins into VREF periphery.
 * @param instance - VREF instance number (0 is expected)
 */
void init_vref_pins(uint32_t instance);
/*!
 * @brief VREF method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for VREF periphery.
 * @param instance - VREF instance number (0 is expected)
 */
void deinit_vref_pins(uint32_t instance);


/* END pin_mux. */
#endif /* #ifndef __pin_mux_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
